version: "3.8"

services:
  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: backend:1.0
    environment:
      MONGODB_URL: mongodb://mongo:27017
      DATABASE_NAME: weather_app
      SECRET_KEY: 09d25e094faa...
      PORT: "8000"
    ports:
      - "8000:8000"
    deploy:
      replicas: 3

volumes:
  mongo_data: